version: "3.8"
services:
  postgres:
    image: postgres:16-bookworm
    container_name: postgres_productos
    restart: always
    environment:
      POSTGRES_DB: productos
      POSTGRES_USER: user_angel
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"